apiVersion: v1
kind: Namespace
metadata:
  name: finance
  annotations:
    # Описание и владелец
    description: "Namespace для критически важных финансовых сервисов: расчёты, бухгалтерия, отчётность, интеграция с ЦБ/банками"
    owner: "example@propdevelopment.loc"
  # Соответствие и compliance
    compliance/standard: "PCI DSS, ISO 27001, 152-ФЗ"
    data-classification: "confidential"  # напр. public, internal, confidential, secret